spring:
  application:
    name: gatewayService
  cloud:
    gateway:
      routes:
        - id: BookService
          uri:
            http://localhost:8081/
          predicates:
            - Path=/books/**
        - id: TransactionService
          uri:
            http://localhost:8082/
          predicates:
            - Path=/transaction/**
        - id: UserService
          uri:
            http://localhost:8080/
          predicates:
            - Path=/users/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/

server:
  port: 8084

okta:
  oauth2:
    issuer: https://dev-09676956.okta.com/oauth2/default